### ISSUE TITLE
copy and paste is not working

### ISSUE THREAD

**Issue by Jungwoo-An** [m66n/ipaddresscontrollib#15]
it is very important action.

**Comment by m66n** [comment]
What exactly isn't working? If a value that is pasted into a field of the control (via CTRL-V or the context menu) can be interpreted as an integer, then that value will be pasted into that field. Otherwise, the value will be interpreted as a full IP address and pasted into the control starting with the first field. Each field is a distinct TextBox and the text in each TextBox can be copied via CTRL-C or the context menu.
